import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'

const Container = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
  min-height: 100vh;
  padding: 0 0.5rem;

`


const Grid = styled.div`
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: center;
  max-width: 800px;
  margin-top: 3rem;

  @media (max-width: 600px) {
    flex-direction: column;
    width: 100%;
  }

 
`


const Home: NextPage = () => {
  function pm(){
    return console.log(0)
  }

  function cancel(){
    return console.log(1)
  }

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
      </Head>



        <Grid>
  <h3>水道局に
  <ul>
    <li>家族の関係</li>
    <li>氏名</li>
    <li>メールアドレス</li>
    <li>電話番号</li>
    </ul>
    の情報の取得を許可しますか？
    </h3>
   </Grid>

    <Grid><button onClick={pm} >
    <strong>ok</strong>
    </button>
    
    <button onClick={cancel}>
    <strong>no</strong>
    </button>
    </Grid>
    
    </Container>
  )
}
export default Home
