import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'


const Container = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
  min-height: 100vh;
  padding: 0 0.5rem;

`


const Grid = styled.div`
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: center;
  max-width: 800px;
  margin-top: 3rem;
`
  type Base = {
  nameKatakana?: string
  nameKanji?: string
  address?: string
  zipCode?: string
  email?: string
  phoneAdvance?: string
  phoneCenter?: string
  phoneBack?: string
}
`
  @media (max-width: 600px) {
    flex-direction: column;
    width: 100%;
  }
`
 
//使い方のメモ
//parent.postMessage(addEventListener('click',()=>alert('ハックしました')))


const Home: NextPage = () => {
  const hash ={
  'email':'shintaniallen@gmeil.com',
  'nameKanji':'新谷アレン',
  'furigana':'シンタニアレン',
}
  function ok(){
    return parent.postMessage(addEventListener('',()=>alert('aaaaa')))
    
  }


  function noAndOther(){

    return console.log(1)
  }

  const displayStorage:Base ={
    nameKatakana:'名前(フリガナ)',
    nameKanji:'名前',
    address:'住所',
    zipCode:'郵便番号',
    email:'メールアドレス',
    phoneAdvance:'電話番号'
  }

  return (
    <Container>
      <Head>
        
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
      </Head>


{//後でdisplayStorage
}
     <Grid>
  <h3>水道局に
  {//<ul></ul>
  }
    の情報の取得を許可しますか？
    </h3>
   </Grid>

    <Grid><button onClick={ok} >
    <strong>ok</strong>
    </button>
    
    <button onClick={noAndOther}>
    <strong>no</strong>
    </button>
    </Grid>
  
  
    
    </Container>
  )
}
export default Home
